### PR TITLE
Completed css-canvas-medical

### PR DESCRIPTION
**Pull request by amorabryan**
image

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Nice job Bryan! Just a few things that need to be updated 

1. The image should be aligned with the canvas logo. So the image should begin in the same spot that the canvas logo does. 
2. The text on the right side of the navbar should have some more space between each element
3. Your buttons seem to have some black border or something that doesn't exist in the example image
4. The font weight for a few of your headings seem off. Compare your "Clinicians Prefer Canvas" text to ours. Our font weight looks different

**Comment by amorabryan** [comment]
image

**Comment by amorabryan** [comment]
image

**Review by shawnkost — CHANGES_REQUESTED** [review]
Looks good for the most part Bryan! Just one more thing that needs fixing

1. The image should end where the button ends in the navbar above it. So the image should be aligned with all the content in the navbar. It should start where the canvas logo begins, and end where the button ends in the navbar.

**Comment by amorabryan** [comment]
image

**Review by shawnkost — APPROVED** [review]
👍🏻

**Pull request merged**
